### PR TITLE
added IAM group name option for klam sudo configuration

### PR DESCRIPTION
**Pull request by sandeephello**
Added IAM group option in KLAM configuration because currently IAM groups are not generic in terms of naming convention like 

'''
GRP-ADOBE_PLATFORM_AWS_SANDBOX_ADMIN
ADOBE_PLATFORM_AWS_STAGE_ADMIN
'''

due to different convention, KLAM SSH is not working for few AWS accounts i.e. Ethos Sandbox, Moonbean Dev & Prod.

`User Reported issue: - https://jira.corp.adobe.com/browse/ETHOSOPS-524`

### CODE REVIEW

**Comment by sandeephello** [comment]
@ts3ng @matthewdfuller Please review this request. I will also make changes in DCOS private universe & co-ethos-config for this feature.

**Comment by sandeephello** [comment]
Just added two more dependent pull request i.e.

https://git.corp.adobe.com/adobe-platform/co-ethos-config/pull/129/files
https://git.corp.adobe.com/adobe-platform/dcos-universe-private/pull/312

**Comment by ts3ng** [comment]
There will be updates needed to also update the package to intake the new klam installation script: https://git.corp.adobe.com/adobe-platform/dcos-universe-private/blob/master/repo/packages/K/klam-ssh/2/config.json

**Comment by ts3ng** [comment]
okay to merge. but in order to properly integrate the changes, we have to update the references here in the package. https://git.corp.adobe.com/adobe-platform/dcos-universe-private/blob/master/repo/packages/K/klam-ssh/2/marathon.json.mustache#L8  after the merge.

**Comment by sandeephello** [comment]
thanks @ts3ng !! 

@matthewdfuller  Please merge this pull request and share URL.

**Review by matthewdfuller — APPROVED** [review]

**Pull request merged**
