### PR TITLE
Add DC/OS Ansible inventory generator

### PR DESCRIPTION
**Pull request by dharmab**

### CODE REVIEW

**Comment by matthewdfuller** [comment]
@dharmab - is this meant to be run on the clusters or your local machine?

**Comment by dharmab** [comment]
Local machine- I'm rewriting this as a true Ansible dynamic inventory,
though.

**Comment by matthewdfuller** [comment]
Okay, is there a better place we might put it? This repo is primarily for content that needs to go onto the remote hosts and is pulled down by packages, etc. If this is something we can run locally, perhaps we should put it in the corp repo: dcos-infrastructure.

**Comment by dharmab** [comment]
Development moved to https://git.corp.adobe.com/bellamko/dcos-ansible/tree/master/inventory/dcos

**Pull request closed without merging**
